### ISSUE TITLE
getApplicationContext() is null

### ISSUE THREAD

**Issue by abdelillah-tam** [a914-gowtham/LetsChat#10]
App crashes after clicking on GET OTP, the error is getApplicationContext is null,
Why?

**Comment by a914-gowtham** [comment]
Hi @abdelillah-tam, Did you try to run the build on the machine? or it is  debug apk you installed

**Comment by abdelillah-tam** [comment]
@a914-gowtham 
I ran it on my phone through android studio, it crashes, then i ran it on a virtual device, it stops on loading view, and gives me this:

```
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err:     at android.content.ContextWrapper.getApplicationContext(ContextWrapper.java:107)
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err:     at androidx.localbroadcastmanager.content.LocalBroadcastManager.getInstance(LocalBroadcastManager.java:107)
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err:     at com.google.firebase.auth.internal.zzax.zzh(com.google.firebase:firebase-auth@@21.0.1:1)
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err:     at com.google.firebase.auth.internal.zzax.zzg(com.google.firebase:firebase-auth@@21.0.1:1)
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err:     at com.google.firebase.auth.internal.zzf.zze(com.google.firebase:firebase-auth@@21.0.1:6)
2021-11-20 12:10:54.616 2298-2298/com.gowtham.letschat W/System.err:     at com.google.firebase.auth.internal.zzf.zza(com.google.firebase:firebase-auth@@21.0.1:15)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.google.firebase.auth.FirebaseAuth.zzH(com.google.firebase:firebase-auth@@21.0.1:25)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.google.firebase.auth.PhoneAuthProvider.verifyPhoneNumber(com.google.firebase:firebase-auth@@21.0.1:2)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.gowtham.letschat.fragments.login.LoginRepo.setMobile(LoginRepo.kt:49)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.gowtham.letschat.fragments.login.LogInViewModel.setMobile(LogInViewModel.kt:77)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.gowtham.letschat.fragments.login.FLogin.validate(FLogin.kt:77)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.gowtham.letschat.fragments.login.FLogin.setDataInView$lambda-1(FLogin.kt:59)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.gowtham.letschat.fragments.login.FLogin.$r8$lambda$9bRm0uBsNPU4pM-N3HGI5gXumuA(FLogin.kt)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.gowtham.letschat.fragments.login.FLogin$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at android.view.View.performClick(View.java:5198)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at android.view.View$PerformClick.run(View.java:21147)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at android.os.Looper.loop(Looper.java:148)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
2021-11-20 12:10:54.617 2298-2298/com.gowtham.letschat W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by abdelillah-tam** [comment]
@a914-gowtham I found the problem, i've tried to pass the context to **PhoneAuthOptions.newBuilder(auth).setActivity(context)** manually, then it worked well, so the problem in passing it by Dagger dependency i think, do you have any idea or solution?

**Comment by a914-gowtham** [comment]
@abdelillah-tam  passing context can be a workaround just like you did now. but, why i injected MainActivity context instead of passing it is, the callback are removed when the app config. changes ex: screen rotation. that's why i used **@ActivityRetainedScoped**. I will try to reproduce the issue and update the status
```kotlin
  val options = PhoneAuthOptions.newBuilder(auth)
            .setPhoneNumber(number)
            .setTimeout(60L, TimeUnit.SECONDS)
            .setActivity(actContxt)
            .setCallbacks(this)  //this callback
            .build()
        PhoneAuthProvider.verifyPhoneNumber(options)
```
